"""Application-facing persistence errors."""

from .persistence import (
    DuplicateEntityError,
    EntityNotFoundError,
    IntegrityConflictError,
    PersistenceError,
    StaleEntityError,
)
from .queries import (
    ApplicationError,
    AuthenticationError,
    AuthorizationError,
    BookingConflictError,
    BookingExpiredError,
    BookingNotFoundError,
    BookingPolicyError,
    CategoryNotFoundError,
    HandoffError,
    InvalidDateTimeError,
    InvalidScheduleError,
    KnowledgeError,
    PublicProfileNotFoundError,
    QualificationError,
    ServiceNotFoundError,
    TelegramIdentityUnavailableError,
    TenantNotFoundError,
    UnresolvedLocaleError,
)

__all__ = [
    "ApplicationError",
    "AuthenticationError",
    "AuthorizationError",
    "BookingConflictError",
    "BookingExpiredError",
    "BookingNotFoundError",
    "BookingPolicyError",
    "CategoryNotFoundError",
    "DuplicateEntityError",
    "EntityNotFoundError",
    "HandoffError",
    "IntegrityConflictError",
    "InvalidDateTimeError",
    "InvalidScheduleError",
    "KnowledgeError",
    "PersistenceError",
    "PublicProfileNotFoundError",
    "QualificationError",
    "ServiceNotFoundError",
    "StaleEntityError",
    "TelegramIdentityUnavailableError",
    "TenantNotFoundError",
    "UnresolvedLocaleError",
]
