"""Shared domain primitives."""

from .errors import (
    DomainError,
    InvalidStateTransition,
    TenantMismatchError,
    ValidationError,
)
from .events import DomainEvent
from .identifiers import (
    AggregateId,
    BookingDraftId,
    BookingId,
    CategoryId,
    ConversationId,
    CustomerId,
    DocumentId,
    EntityId,
    HandoffId,
    LeadId,
    ResourceId,
    ScheduleId,
    ServiceId,
    SlotHoldId,
    TenantId,
)
from .value_objects import (
    Citation,
    Confidence,
    IdempotencyKey,
    Locale,
    Money,
    PhoneNumber,
    PriceMode,
    PricePresentation,
    TimeRange,
    ensure_aware,
)

__all__ = [
    "AggregateId",
    "BookingDraftId",
    "BookingId",
    "CategoryId",
    "Citation",
    "Confidence",
    "ConversationId",
    "CustomerId",
    "DocumentId",
    "DomainError",
    "DomainEvent",
    "EntityId",
    "HandoffId",
    "IdempotencyKey",
    "InvalidStateTransition",
    "LeadId",
    "Locale",
    "Money",
    "PhoneNumber",
    "PriceMode",
    "PricePresentation",
    "ResourceId",
    "ScheduleId",
    "ServiceId",
    "SlotHoldId",
    "TenantId",
    "TenantMismatchError",
    "TimeRange",
    "ValidationError",
    "ensure_aware",
]
