# ruff: noqa: E501
"""initial_phase_2_schema

Revision ID: 0001_phase2
Revises:
Create Date: 2026-08-02 23:40:50.428170
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0001_phase2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensions are shared database capabilities; downgrade deliberately preserves them.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("default_locale", sa.String(length=10), nullable=False),
        sa.Column("supported_locales", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("settings_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','inactive')", name=op.f("ck_tenants_status_allowed")
        ),
        sa.CheckConstraint(
            "settings_version >= 1", name=op.f("ck_tenants_settings_version_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=100), nullable=False),
        sa.Column("target_id", sa.String(length=100), nullable=False),
        sa.Column("safe_diff", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_audit_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_tenant_occurred",
        "audit_events",
        ["tenant_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "business_schedules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_business_schedules_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_schedules")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_business_schedules_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_business_schedules_tenant_id_name")),
    )
    op.create_index(
        "ix_business_schedules_tenant_active",
        "business_schedules",
        ["tenant_id", "active"],
        unique=False,
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("phone_raw", sa.String(length=32), nullable=True),
        sa.Column("phone_e164", sa.String(length=16), nullable=True),
        sa.Column("phone_verified", sa.Boolean(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("privacy_notice_version", sa.String(length=50), nullable=True),
        sa.Column("privacy_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contact_consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','blocked','anonymized')", name=op.f("ck_customers_status_allowed")
        ),
        sa.CheckConstraint(
            "(privacy_notice_version IS NULL) = (privacy_accepted_at IS NULL)",
            name=op.f("ck_customers_privacy_acceptance_pair"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_customers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_customers_tenant_id_id")),
    )
    op.create_index(
        "ix_customers_tenant_status", "customers", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "published_at IS NULL OR status = 'ready'",
            name=op.f("ck_knowledge_documents_publication_requires_ready"),
        ),
        sa.CheckConstraint(
            "status IN ('uploaded','parsing','chunking','embedding','ready','failed','archived')",
            name=op.f("ck_knowledge_documents_status_allowed"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_knowledge_documents_version_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_knowledge_documents_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_documents")),
        sa.UniqueConstraint(
            "tenant_id",
            "checksum",
            "version",
            name=op.f("uq_knowledge_documents_tenant_id_checksum_version"),
        ),
        sa.UniqueConstraint(
            "tenant_id", "id", "version", name=op.f("uq_knowledge_documents_tenant_id_id_version")
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_knowledge_documents_tenant_id_id")),
    )
    op.create_index(
        "ix_knowledge_documents_tenant_searchable",
        "knowledge_documents",
        ["tenant_id", "locale"],
        unique=False,
        postgresql_where=sa.text("status = 'ready' AND published_at IS NOT NULL"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','processing','published','failed')",
            name=op.f("ck_outbox_events_status_allowed"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_outbox_events_attempts_nonnegative")),
        sa.CheckConstraint(
            "event_version >= 1", name=op.f("ck_outbox_events_event_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_outbox_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint(
            "tenant_id", "event_id", name=op.f("uq_outbox_events_tenant_id_event_id")
        ),
    )
    op.create_index(
        "ix_outbox_events_tenant_pending",
        "outbox_events",
        ["tenant_id", "available_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "service_categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_service_categories_sort_order_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_service_categories_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_categories")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_service_categories_tenant_id_id")),
    )
    op.create_index(
        "ix_service_categories_tenant_active_sort",
        "service_categories",
        ["tenant_id", "active", "sort_order"],
        unique=False,
    )
    op.create_table(
        "channel_identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("external_user_id", sa.String(length=100), nullable=False),
        sa.Column("external_chat_id", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customers.tenant_id", "customers.id"],
            name=op.f("fk_channel_identities_tenant_id_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_channel_identities_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel_identities")),
        sa.UniqueConstraint(
            "tenant_id",
            "channel",
            "external_user_id",
            name=op.f("uq_channel_identities_tenant_id_channel_external_user_id"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_channel_identities_tenant_id_id")),
    )
    op.create_index(
        "ix_channel_identities_tenant_customer",
        "channel_identities",
        ["tenant_id", "customer_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("document_version", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', coalesce(chunk_text, ''))", persisted=True),
            nullable=False,
        ),
        sa.Column("embedding", Vector(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=False),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_knowledge_chunks_ordinal_nonnegative")),
        sa.CheckConstraint(
            "token_count >= 0", name=op.f("ck_knowledge_chunks_token_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "document_id", "document_version"],
            [
                "knowledge_documents.tenant_id",
                "knowledge_documents.id",
                "knowledge_documents.version",
            ],
            name=op.f(
                "fk_knowledge_chunks_tenant_id_document_id_document_version_knowledge_documents"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_knowledge_chunks_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
        sa.UniqueConstraint(
            "tenant_id",
            "document_id",
            "document_version",
            "ordinal",
            name=op.f("uq_knowledge_chunks_tenant_id_document_id_document_version_ordinal"),
        ),
    )
    op.create_index(
        "ix_knowledge_chunks_search_vector",
        "knowledge_chunks",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_knowledge_chunks_tenant_document",
        "knowledge_chunks",
        ["tenant_id", "document_id", "document_version"],
        unique=False,
    )
    op.create_table(
        "resources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_resources_capacity_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "schedule_id"],
            ["business_schedules.tenant_id", "business_schedules.id"],
            name=op.f("fk_resources_tenant_id_schedule_id_business_schedules"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_resources_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resources")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_resources_tenant_id_id")),
    )
    op.create_index(
        "ix_resources_tenant_active", "resources", ["tenant_id", "active"], unique=False
    )
    op.create_table(
        "schedule_intervals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start_local", sa.Time(), nullable=False),
        sa.Column("end_local", sa.Time(), nullable=False),
        sa.Column("interval_type", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "interval_type IN ('open','break')",
            name=op.f("ck_schedule_intervals_interval_type_allowed"),
        ),
        sa.CheckConstraint(
            "start_local < end_local", name=op.f("ck_schedule_intervals_time_order_valid")
        ),
        sa.CheckConstraint(
            "weekday BETWEEN 0 AND 6", name=op.f("ck_schedule_intervals_weekday_valid")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "schedule_id"],
            ["business_schedules.tenant_id", "business_schedules.id"],
            name=op.f("fk_schedule_intervals_tenant_id_schedule_id_business_schedules"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_schedule_intervals_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_intervals")),
    )
    op.create_index(
        "ix_schedule_intervals_tenant_schedule",
        "schedule_intervals",
        ["tenant_id", "schedule_id", "weekday"],
        unique=False,
    )
    op.create_table(
        "schedule_overrides",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.Column("intervals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "(closed AND jsonb_array_length(intervals) = 0) OR (NOT closed AND jsonb_array_length(intervals) > 0)",
            name=op.f("ck_schedule_overrides_override_intervals_valid"),
        ),
        sa.CheckConstraint(
            "starts_on <= ends_on", name=op.f("ck_schedule_overrides_date_order_valid")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "schedule_id"],
            ["business_schedules.tenant_id", "business_schedules.id"],
            name=op.f("fk_schedule_overrides_tenant_id_schedule_id_business_schedules"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_schedule_overrides_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_overrides")),
    )
    op.create_index(
        "ix_schedule_overrides_tenant_schedule_dates",
        "schedule_overrides",
        ["tenant_id", "schedule_id", "starts_on", "ends_on"],
        unique=False,
    )
    op.create_table(
        "services",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("descriptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("buffer_seconds", sa.Integer(), nullable=False),
        sa.Column("price_mode", sa.String(length=32), nullable=False),
        sa.Column("price_min_minor", sa.BigInteger(), nullable=True),
        sa.Column("price_max_minor", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("preparation_notes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("eligibility_notes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("bookable", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(price_mode IN ('exact','starting_from') AND price_min_minor IS NOT NULL AND price_max_minor IS NULL AND currency IS NOT NULL) OR (price_mode = 'range' AND price_min_minor IS NOT NULL AND price_max_minor IS NOT NULL AND price_min_minor <= price_max_minor AND currency IS NOT NULL) OR (price_mode IN ('quote_required','not_displayed') AND price_min_minor IS NULL AND price_max_minor IS NULL AND currency IS NULL)",
            name=op.f("ck_services_price_shape_valid"),
        ),
        sa.CheckConstraint(
            "price_mode IN ('exact','range','starting_from','quote_required','not_displayed')",
            name=op.f("ck_services_price_mode_allowed"),
        ),
        sa.CheckConstraint("buffer_seconds >= 0", name=op.f("ck_services_buffer_nonnegative")),
        sa.CheckConstraint("duration_seconds > 0", name=op.f("ck_services_duration_positive")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_services_version_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "category_id"],
            ["service_categories.tenant_id", "service_categories.id"],
            name=op.f("fk_services_tenant_id_category_id_service_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_services_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_services_tenant_id_code")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_services_tenant_id_id")),
    )
    op.create_index(
        "ix_services_tenant_category_active",
        "services",
        ["tenant_id", "category_id", "active"],
        unique=False,
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_scope", sa.String(length=100), nullable=False),
        sa.Column("idempotency_value", sa.String(length=255), nullable=False),
        sa.Column("idempotency_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("service_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("customer_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("tenant_id"), "="),
            (sa.column("resource_id"), "="),
            (sa.text("tstzrange(start_at, end_at, '[)')"), "&&"),
            where=sa.text(
                "resource_id IS NOT NULL AND status IN ('held','confirmed','reschedule_pending')"
            ),
            using="gist",
            name="ex_bookings_resource_active_overlap",
        ),
        sa.CheckConstraint(
            "status IN ('draft','held','confirmed','completed','cancelled','no_show','reschedule_pending','expired')",
            name=op.f("ck_bookings_status_allowed"),
        ),
        sa.CheckConstraint("start_at < end_at", name=op.f("ck_bookings_time_order_valid")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customers.tenant_id", "customers.id"],
            name=op.f("fk_bookings_tenant_id_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "resource_id"],
            ["resources.tenant_id", "resources.id"],
            name=op.f("fk_bookings_tenant_id_resource_id_resources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "service_id"],
            ["services.tenant_id", "services.id"],
            name=op.f("fk_bookings_tenant_id_service_id_services"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_bookings_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_bookings_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "idempotency_scope",
            "idempotency_value",
            name=op.f("uq_bookings_tenant_id_idempotency_scope_idempotency_value"),
        ),
    )
    op.create_index(
        "ix_bookings_tenant_customer_start",
        "bookings",
        ["tenant_id", "customer_id", "start_at"],
        unique=False,
    )
    op.create_index(
        "ix_bookings_tenant_status_start",
        "bookings",
        ["tenant_id", "status", "start_at"],
        unique=False,
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("channel_identity_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("active_workflow", sa.String(length=100), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active_bot','handoff_queued','human_active','closed')",
            name=op.f("ck_conversations_status_allowed"),
        ),
        sa.CheckConstraint(
            "summary_version >= 0", name=op.f("ck_conversations_summary_version_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "channel_identity_id"],
            ["channel_identities.tenant_id", "channel_identities.id"],
            name=op.f("fk_conversations_tenant_id_channel_identity_id_channel_identities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customers.tenant_id", "customers.id"],
            name=op.f("fk_conversations_tenant_id_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_conversations_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_conversations_tenant_id_id")),
    )
    op.create_index(
        "ix_conversations_tenant_customer",
        "conversations",
        ["tenant_id", "customer_id"],
        unique=False,
    )
    op.create_index(
        "ix_conversations_tenant_last_message",
        "conversations",
        ["tenant_id", "last_message_at"],
        unique=False,
    )
    op.create_table(
        "booking_status_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=False),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sequence >= 1", name=op.f("ck_booking_status_history_sequence_positive")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "booking_id"],
            ["bookings.tenant_id", "bookings.id"],
            name=op.f("fk_booking_status_history_tenant_id_booking_id_bookings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_booking_status_history_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_status_history")),
        sa.UniqueConstraint(
            "booking_id", "sequence", name=op.f("uq_booking_status_history_booking_id_sequence")
        ),
    )
    op.create_index(
        "ix_booking_history_tenant_booking",
        "booking_status_history",
        ["tenant_id", "booking_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "handoff_cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("reason_code", sa.String(length=100), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("assignee_id", sa.String(length=100), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("response_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued','claimed','resolved','reopened','cancelled')",
            name=op.f("ck_handoff_cases_status_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "conversation_id"],
            ["conversations.tenant_id", "conversations.id"],
            name=op.f("fk_handoff_cases_tenant_id_conversation_id_conversations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_handoff_cases_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_handoff_cases")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_handoff_cases_tenant_id_id")),
    )
    op.create_index(
        "ix_handoff_cases_tenant_open",
        "handoff_cases",
        ["tenant_id", "status"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued','claimed','reopened')"),
    )
    op.create_table(
        "leads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("schema_code", sa.String(length=100), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=True),
        sa.Column("score_explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('new','qualifying','qualified','contacted','converted','unqualified','closed')",
            name=op.f("ck_leads_status_allowed"),
        ),
        sa.CheckConstraint("schema_version >= 1", name=op.f("ck_leads_schema_version_positive")),
        sa.CheckConstraint(
            "score IS NULL OR score BETWEEN 0 AND 100", name=op.f("ck_leads_score_valid")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "conversation_id"],
            ["conversations.tenant_id", "conversations.id"],
            name=op.f("fk_leads_tenant_id_conversation_id_conversations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customers.tenant_id", "customers.id"],
            name=op.f("fk_leads_tenant_id_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_leads_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_leads_tenant_id_id")),
    )
    op.create_index(
        "ix_leads_tenant_status_priority",
        "leads",
        ["tenant_id", "status", "priority"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("channel_account_id", sa.String(length=100), nullable=False),
        sa.Column("external_update_id", sa.String(length=100), nullable=True),
        sa.Column("channel_message_id", sa.String(length=100), nullable=True),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("redacted_text", sa.Text(), nullable=True),
        sa.Column("raw_payload_reference", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "conversation_id"],
            ["conversations.tenant_id", "conversations.id"],
            name=op.f("fk_messages_tenant_id_conversation_id_conversations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_messages_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "tenant_id",
            "channel",
            "channel_account_id",
            "external_update_id",
            name=op.f("uq_messages_tenant_id_channel_channel_account_id_external_update_id"),
        ),
    )
    op.create_index(
        "ix_messages_tenant_conversation_created",
        "messages",
        ["tenant_id", "conversation_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_tenant_conversation_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_leads_tenant_status_priority", table_name="leads")
    op.drop_table("leads")
    op.drop_index(
        "ix_handoff_cases_tenant_open",
        table_name="handoff_cases",
        postgresql_where=sa.text("status IN ('queued','claimed','reopened')"),
    )
    op.drop_table("handoff_cases")
    op.drop_index("ix_booking_history_tenant_booking", table_name="booking_status_history")
    op.drop_table("booking_status_history")
    op.drop_index("ix_conversations_tenant_last_message", table_name="conversations")
    op.drop_index("ix_conversations_tenant_customer", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_bookings_tenant_status_start", table_name="bookings")
    op.drop_index("ix_bookings_tenant_customer_start", table_name="bookings")
    op.drop_table("bookings")
    op.drop_index("ix_services_tenant_category_active", table_name="services")
    op.drop_table("services")
    op.drop_index("ix_schedule_overrides_tenant_schedule_dates", table_name="schedule_overrides")
    op.drop_table("schedule_overrides")
    op.drop_index("ix_schedule_intervals_tenant_schedule", table_name="schedule_intervals")
    op.drop_table("schedule_intervals")
    op.drop_index("ix_resources_tenant_active", table_name="resources")
    op.drop_table("resources")
    op.drop_index("ix_knowledge_chunks_tenant_document", table_name="knowledge_chunks")
    op.drop_index(
        "ix_knowledge_chunks_search_vector", table_name="knowledge_chunks", postgresql_using="gin"
    )
    op.drop_table("knowledge_chunks")
    op.drop_index("ix_channel_identities_tenant_customer", table_name="channel_identities")
    op.drop_table("channel_identities")
    op.drop_index("ix_service_categories_tenant_active_sort", table_name="service_categories")
    op.drop_table("service_categories")
    op.drop_index(
        "ix_outbox_events_tenant_pending",
        table_name="outbox_events",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("outbox_events")
    op.drop_index(
        "ix_knowledge_documents_tenant_searchable",
        table_name="knowledge_documents",
        postgresql_where=sa.text("status = 'ready' AND published_at IS NOT NULL"),
    )
    op.drop_table("knowledge_documents")
    op.drop_index("ix_customers_tenant_status", table_name="customers")
    op.drop_table("customers")
    op.drop_index("ix_business_schedules_tenant_active", table_name="business_schedules")
    op.drop_table("business_schedules")
    op.drop_index("ix_audit_events_tenant_occurred", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("tenants")
    # ### end Alembic commands ###
