"""add_tenant_public_profiles

Revision ID: 0002_phase3
Revises: 0001_phase2
Create Date: 2026-08-03 17:30:35.945776
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_phase3"
down_revision: str | None = "0001_phase2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant_public_profiles",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("descriptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("public_phone", sa.String(length=32), nullable=True),
        sa.Column("public_email", sa.String(length=254), nullable=True),
        sa.Column("website_url", sa.String(length=500), nullable=True),
        sa.Column("addresses", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("service_areas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parking_guidance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payment_methods", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warranty_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("appointment_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_tenant_public_profiles_version_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "schedule_id"],
            ["business_schedules.tenant_id", "business_schedules.id"],
            name=op.f("fk_tenant_public_profiles_tenant_id_schedule_id_business_schedules"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_public_profiles_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_tenant_public_profiles")),
    )
    op.create_index(
        "ix_tenant_public_profiles_tenant_schedule",
        "tenant_public_profiles",
        ["tenant_id", "schedule_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tenant_public_profiles_tenant_schedule", table_name="tenant_public_profiles")
    op.drop_table("tenant_public_profiles")
    # ### end Alembic commands ###
